### ISSUE TITLE
SET

### ISSUE THREAD

**Issue by tkirchm** [Bouni/node-red-contrib-luxtronik2-ws#7]
Hi,
Is it possible to also send SET and SAVE like it is described in https://www.loxwiki.eu/pages/viewpage.action?pageId=18219339?

I would like to set Einstellungen -> Heizkreis or Warmwasser from Auto to off and the other way around.

**Comment by Bouni** [comment]
Its definitely possible but not implemented (I will not implement it because I no longer use node-red)

**Comment by tkirchm** [comment]
Python would be even better. I read that you are now programming for Home-Assistant. 
Is there a project too?
I couldn’t get the SET to work because the ID is always changing.

**Comment by Bouni** [comment]
Yes, actually I've submitted a PR back in Octover for official Luxtronik Support in HA:

https://github.com/home-assistant/home-assistant/pull/27230
