### ISSUE TITLE
Uncaught Exception - WebSocket is not open: readyState 0

### ISSUE THREAD

**Issue by Henriettel** [Bouni/node-red-contrib-luxtronik2-ws#9]
i think the stacktrace might be enough. Happens every 2-3 days.
`
Mar 03 18:40:57 loxberry node-red[8542]: 3 Mar 18:40:57 - [red] Uncaught Exception:
Mar 03 18:40:57 loxberry node-red[8542]: 3 Mar 18:40:57 - Error: WebSocket is not open: readyState 0 (CONNECTING)
Mar 03 18:40:57 loxberry node-red[8542]:     at WebSocket.send (/usr/lib/node_modules/node-red-contrib-luxtronik2-ws/node_modules/ws/lib/websocket.js:327:13)
Mar 03 18:40:57 loxberry node-red[8542]:     at WebSocket.open (/usr/lib/node_modules/node-red-contrib-luxtronik2-ws/luxtronik2-ws.js:38:21)
Mar 03 18:40:57 loxberry node-red[8542]:     at WebSocket.emit (events.js:311:20)
Mar 03 18:40:57 loxberry node-red[8542]:     at WebSocket.setSocket (/usr/lib/node_modules/node-red-contrib-luxtronik2-ws/node_modules/ws/lib/websocket.js:172:10)
Mar 03 18:40:57 loxberry node-red[8542]:     at ClientRequest.<anonymous> (/usr/lib/node_modules/node-red-contrib-luxtronik2-ws/node_modules/ws/lib/websocket.js:646:15)
Mar 03 18:40:57 loxberry node-red[8542]:     at ClientRequest.emit (events.js:311:20)
Mar 03 18:40:57 loxberry node-red[8542]:     at Socket.socketOnData (_http_client.js:510:11)
Mar 03 18:40:57 loxberry node-red[8542]:     at Socket.emit (events.js:311:20)
Mar 03 18:40:57 loxberry node-red[8542]:     at addChunk (_stream_readable.js:294:12)
Mar 03 18:40:57 loxberry node-red[8542]:     at readableAddChunk (_stream_readable.js:275:11)
Mar 03 18:40:57 loxberry systemd[1]: node-red.service: Succeeded.
`
Edit: I think i got the problem:
If you're running the command
`npm install -g node-red-contrib-luxtronik2-ws`

you get a version of the package, but that does not reflect the version of this repo.

The package from npm has no try-catch block around line 38 and 39.

Can you please update the npm package?
Version in 
`/usr/lib/node_modules/node-red-contrib-luxtronik2-ws/package.json`
says 0.1.1 but the code does not reflect the repo.

**Comment by Bouni** [comment]
Just bumped the version and pulished, check if that solves your issue.

**Comment by Henriettel** [comment]
Worked perfectly, the try catch block now exists. Thank you for the fast response!
